[slime-mould.general]
spawn_mode = "point"
trail_weight = 5.0
diffuse_rate = 3.0
decay_rate = 10.0

[[slime-mould.species]]
agents = 250000
move_speed = 20.0
turn_speed = 2.0
sensor_angle_degrees = 30.0
sensor_offset_dst = 35.0
sensor_size = 1
color = [1, 1, 1, 0]
